### ISSUE TITLE
Use width of terminal window

### ISSUE THREAD

**Issue by nomeata** [roelvandijk/terminal-progress-bar#1]
It would be great if you library could, in a portable manner, find out the width of the current terminal for bars that should span the whole terminal.

Alternatively, if you think this should not belong in the library, the documentation should give pointers on where to find this functionality.

**Comment by roelvandijk** [comment]
It's done! After 4 1/2 years...: 8c341939425b270f191409372cba05a787eb992b

@wenkokke pointed me in the right direction in #18.
