### ISSUE TITLE
Needs bump of HUnit dependency

### ISSUE THREAD

**Issue by nomeata** [roelvandijk/terminal-progress-bar#11]
Hi,

the test suite depends on `HUnit <1.3`, but `HUnit-1.3` is the latest on hackage.

Thanks,
Joachim

**Comment by bergmark** [comment]
The test-suite for this package has been disabled in stackage because of this outdated dependency. If a fix is published to hackage can you please ping me?

Thanks!

**Comment by roelvandijk** [comment]
Pinging @bergmark. The test-suite should build again.

**Comment by bergmark** [comment]
Thanks!
