### ISSUE TITLE
progressBar doesn't check for 0 input

### ISSUE THREAD

**Issue by wenkokke** [roelvandijk/terminal-progress-bar#17]
The library doesn't check for `0` input for the "amount of work done", meaning that if you call any of the `progressBar` functions with `0` as the 4th argument:

```haskell
progressBar prefLbl postLbl windowHeight workDone workTotal
```

You get a nice `prefLbl [exe: Ratio has zero denominator` error.

**Comment by roelvandijk** [comment]
That should definitely be fixed. Thanks for the report!

**Comment by roelvandijk** [comment]
The problem was in the `percentage` label function.
