### ISSUE TITLE
Automatically determine the terminal width

### ISSUE THREAD

**Issue by wenkokke** [roelvandijk/terminal-progress-bar#18]
It may be a nice feature to integrate the progressbar code with the `terminal-size` package, so that you can call a function – e.g. `progressBar'` – to get a progress bar which is automatically sized to the maximum possible size.

**Comment by wenkokke** [comment]
See https://hackage.haskell.org/package/terminal-size

**Comment by roelvandijk** [comment]
This is a very good idea! This has been requested before (#1). I like the simplicity of the `terminal-size` package.

**Comment by roelvandijk** [comment]
Implemented in 8c341939425b270f191409372cba05a787eb992b! 

Thanks for suggesting the excellent `terminal-size` package.
