### ISSUE TITLE
Generalize the ProgressBar type signature

### ISSUE THREAD

**Issue by wenkokke** [roelvandijk/terminal-progress-bar#19]
The type signature for ProgressBar requires Integer. It may be nicer to have this be a more general `Num` constraint. For instance, `length` returns an `Int`, and therefore is not easily compatible with the progress bar functions under the current typing.

**Comment by roelvandijk** [comment]
I see the problem. 

I think the choice is between a fixed type or a polymorphic type. 

With the fixed type we can still decide whether it should be `Int` or `Integer`. Perhaps the current `Integer` is a bit overkill. An advantage of a fixed type is much better type inference.

With a polymorphic type constraint by `Num` we let the user decide. The downside is that the user __must__ decide on a type. It is also a bit harder to reason about the correctness of the code. What if the user decides to use `Word8`?

Which choice would be most convenient for you?

**Comment by roelvandijk** [comment]
I have decided to use the `Int` type for progress bars instead of `Integer`. This should meet the need of most users while still having a simple interface and keep type inference problems to a minimum.
