### ISSUE TITLE
Update the test suite to HUnit 1.6

### ISSUE THREAD

**Issue by DanBurton** [roelvandijk/terminal-progress-bar#23]
The Stackage nightly build process is currently not building or running this package's test suite due to its constraint `HUnit < 1.6`.

**Comment by roelvandijk** [comment]
Thanks for the heads up Dan. I removed upper bound constraints on most dependencies and [released version 0.1.2](https://hackage.haskell.org/package/terminal-progress-bar-0.1.2).

I will fix breakage resulting from newer dependencies when necessary.  I suspect that will be much less work than continuously updating upper bounds when newer versions are released.

Would it be useful if I retroactively removed the `HUnit < 1.6` constraint for version 0.1.1.1 using the `edit Cabal file metadata feature` of hackage?

**Comment by DanBurton** [comment]
That's up to you; the new version you released is sufficient for Stackage's purposes. Thanks!
