### ISSUE TITLE
Time-aware progress bar

### ISSUE THREAD

**Issue by nomeata** [roelvandijk/terminal-progress-bar#24]
I started using `incProgress` in my program that processes a list of about a million entries, but I am wondering if I just introduced a bottle neck: I was optimistically assuming that the automatically managed progress bar would avoid updating the state too often and make calls to `incProgress` cheap if they happen in quick succession, only updating the output, say, once every ⅒th second.

But now I look at the code of `reportProgress` and it seems that this is not the case; so here is a feature request :-)

And if you indeed implement this feature request and start paying attention to time, you could also add `Label` functions that display useful things like the estimated time to completion. The `progress` command line utility, which adds progress bars to arbitrary file-processing processes, can serve as inspiration.

**Comment by roelvandijk** [comment]
That would be a good feature to have.

I will have to do some tests to see if rate limiting makes sense. I suspect it will. The timing calculations should be faster than rendering the progress bar.

Making timing info available to the `Label` functions is a nice bonus.

I will have to think about the API a bit. I'm open to suggestions :-)

**Comment by roelvandijk** [comment]
Hey @nomeata, does the approach taken in the 0.4-preview branch solve your problem?

The rate limiting is quite effective and you get simple remaining time prediction. I did change the interface a bit. Most importantly it no longer spawns a thread. Instead, the progress-bar work is done by the caller.

**Comment by nomeata** [comment]
Yeah, that seems to work for me!

**Comment by roelvandijk** [comment]
I just released [version 0.4](http://hackage.haskell.org/package/terminal-progress-bar-0.4) on hackage which contains the time-aware features.
