### ISSUE TITLE
Clear progress bar when finished

### ISSUE THREAD

**Issue by rvl** [roelvandijk/terminal-progress-bar#25]
Is it possible to add a style option to clear the progress bar once it has finished, rather than printing a newline? Thanks.

**Comment by roelvandijk** [comment]
I implemented an option to clear the progress bar once finished in a15bca042f9651958ee0a202aad24c5047373028. It uses an ANSI escape code. Let me know if this works for you.

**Comment by rvl** [comment]
Thanks! The previous code printed spaces to the width of the progress bar, but it looks like `\ESC[K` will work great.

**Comment by roelvandijk** [comment]
Great!
