### ISSUE TITLE
Consider adding to Stackage

### ISSUE THREAD

**Issue by ndmitchell** [roelvandijk/terminal-progress-bar#26]
This library is great, and has a great result - very happy with it. Would you consider adding it to Stackage? The instructions to add it are at https://github.com/commercialhaskell/stackage/blob/master/MAINTAINERS.md - it basically ensure it's compatible with all other packages, and makes our lives a bit easier.

For info, you can see where we're using the code in https://github.com/digital-asset/daml/blob/292d2b40b41bf64841913df48441b4597e6f6c34/daml-assistant/src/DAML/Assistant/Install.hs

**Comment by roelvandijk** [comment]
Hi Neil,

It's nice to hear that this package is useful! I will definitely try adding it to Stackage.

I think the following steps need to be completed:
- [ ] Write a stack.yaml file
- [ ] Setup CI (with Travis) with support for multiple GHC versions
- [ ] Submit package to stackage

It will probably take some time because I do not regularly use stack.

**Comment by ndmitchell** [comment]
I never write a stack.yaml file. Adding a CI is quite handy, but not essential - basically adding it to Stackage is like a CI. You can also already view the results from the Matrix CI - https://matrix.hackage.haskell.org/#/package/terminal-progress-bar - seems your code builds on a variety of GHC already - so you are already safe. Submitting to Stackage is a one liner, and doesn't require using stack (I don't either) so if I were you I'd just submit it anyway.

Of course, writing a CI system is always useful, so whatever you want.

**Comment by roelvandijk** [comment]
Good points! I will write the one liner :-)

**Comment by roelvandijk** [comment]
This part gives me problems:
- [ ] On your own machine, in a _new directory_, you have successfully run the following set of commands (replace `$package` with the name of the package that is submitted, and `$version` with the version of the package you want to get into Stackage):

      stack unpack $package-$version  # $version is optional
      stack init --resolver nightly
      stack build --resolver nightly --haddock --test --bench --no-run-benchmarks

I get this error:
```
$ stack build --resolver nightly --haddock --test --bench --no-run-benchmarks
Note: Enabling Nix integration, as it is required under NixOS
Selected resolver: nightly-2019-04-23
error: attribute 'ghc864' missing, at (string):1:43
(use '--show-trace' to show detailed location information)
```
Could this simply be related to me using NixOS? I'm still comfortable submitting the pull request if you can finish this step succesfully on one of your machines.

**Comment by ndmitchell** [comment]
It works close enough that I'd be confident saying it works for you. There are two slight issues;

* The `--haddock` flag causes issues on Windows.
* GHC segfaults when running TemplateHaskell on Windows with the GHC in Nightly.

Neither are a problem with your package, so I'd submit it happily.

**Comment by roelvandijk** [comment]
It was merged into stackage. Thanks for the advice Neil.
