### ISSUE TITLE
Base dependency not strict enough

### ISSUE THREAD

**Issue by nomeata** [roelvandijk/terminal-progress-bar#6]
If you look at https://s3.amazonaws.com/archive.travis-ci.org/jobs/13514396/log.txt you’ll see that it failed to build:

```
Failed to install terminal-progress-bar-0.0.1.3
Last 10 lines of the build log ( /home/travis/.cabal/logs/terminal-progress-bar-0.0.1.3.log ):
Preprocessing library terminal-progress-bar-0.0.1.3...
Preprocessing test suites for terminal-progress-bar-0.0.1.3...
Building terminal-progress-bar-0.0.1.3...
[1 of 1] Compiling System.ProgressBar ( src/System/ProgressBar.hs, dist/build/System/ProgressBar.o )

src/System/ProgressBar.hs:20:31:
    Module `Data.String' does not export `String'
```

`Data.String` exports `String` only since `base-4.4`, so you might want to change your build-depends, or simply use `String` from the `Prelude`.

You might also be interested in https://github.com/hvr/multi-ghc-travis to test your library easily against many versions of GHC, this makes supporting old versions much easier.

**Comment by roelvandijk** [comment]
The immediate problem should be solved. But continuous integration support with multiple GHC's would be really nice.

Pull requests are welcome ;-)

**Comment by roelvandijk** [comment]
Closing this issue since the immediate issue is solved. Created a new issue for the continuous integration (#21).
